local addonName, AA = ...

AA.Words = {
    "PORTAIL", "MURLOC", "TITAN", "LUNE", "FORGE",
    "DRAGON", "RUNE", "ANCRE", "DAGUE", "BANQUE",
    "GOBELIN", "GLACE", "OMBRE", "TORCHE", "MAGE",
    "CRYPTE", "GRIFFON", "HORDE", "ALLIANCE", "TOTEM",
    "FEL", "NAGA", "ARCANE", "RELIQUE", "BATEAU",
    "SABRE", "MONTURE", "AUBERGE", "MARTEAU", "COURONNE",
    "ELFE", "ORC", "NAIN", "GNOME", "TROLL",
    "DRAENEI", "PANDAREN", "MORT", "VIE", "CHAOS",
    "PRÊTRE", "VOLEUR", "PALADIN", "CHASSEUR", "DÉMON",
    "LANCE", "BOUCLIER", "PRISON", "TEMPLE", "CAVERNE",
    "SABLE", "MER", "VOLCAN", "FLEUR", "CHAMPION",
    "BANNIÈRE", "BOSS", "DONJON", "RAID", "TRÉSOR",
    "ROYAUME", "CITADELLE", "ESPION", "AGENT", "MISSION",
    "DÉSERTEUR", "ARCHIVE", "DOSSIER", "SCEAU", "COURRIER",
    "POISON", "MASQUE", "TAVERNE", "NAVIRE", "CRISTAL",
    "FANTÔME", "PIÈGE", "CLÉ", "CARTE", "SECRET",
    "HÉROS", "INVASION", "PORT", "MARCHAND", "RAVENHOLDT",
    "HURLEVENT", "ORGRIMMAR", "KUL TIRAS", "DALARAN", "AZERITE"
}
